name: Deploy to GitHub Pages

# Fire when your Excel-update workflow completes (or manually)
on:
  workflow_run:
    workflows: ["Auto Update Excel File"]   # <-- exact name of your update job
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write      # allow publish
      id-token: write   # required by configure-pages

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .          # bundle your repo root (including the updated XLSX)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          environment: github-pages
