name: Auto Update Excel File

on:
  schedule:
    - cron: '0 * * * *'    # every hour on the hour
  workflow_dispatch:      # manual trigger

permissions:
  contents: write         # allow pushes

jobs:
  refresh-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Download latest Excel from SharePoint
        run: python download.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # only commit if downloaded_file.xlsx differs
          if git diff --quiet downloaded_file.xlsx; then
            echo "✅ No change detected"
          else
            git add downloaded_file.xlsx
            git commit -m "chore: automated update of downloaded_file.xlsx"
            git push origin gh-pages
          fi
